# Generated by Django 4.2.15 on 2024-09-04 15:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contactrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpost',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
