# Generated by Django 4.2.15 on 2024-09-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_travelpost_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
